optimizer: {
  type: AdamW,
  kwargs: {
  lr: 0.001,
  weight_decay: 0.05}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 400,
    initial_epochs: 10}}

dataset: {
  train: { _base_: cfgs/dataset/ModelNet40_linear_probing.yaml,
            others: {partition: 'train', num_points: 1024}},
  val: { _base_: cfgs/dataset/ModelNet40_linear_probing.yaml,
            others: {partition: 'test', num_points: 1024}},
  test: { _base_: cfgs/dataset/ModelNet40_linear_probing.yaml,
            others: {partition: 'test', num_points: 1024}}}

model : {
  NAME: PointBYOLClassifier,
  cls_dim: 40,
  encoder: {
    NAME: PointNetEncoder,
    space_transform: False,
    feature_transform: False,
  },
}

total_bs: 128
step_per_update: